org: donutranger
app: haris-be
service: mh-billplz
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [BillTable, Arn]
  environment:
    BILL_TABLE: ${self:custom.tableName}

functions:
  getBill:
    handler: handlers.getBill
    events:
      - httpApi:
          path: /getBill/{id}
          method: get
  createBill:
    handler: handlers.createBill
    events:
      - httpApi:
          path: /createBill
          method: post
  processBill:
    handler: handlers.processBill
    events:
      - httpApi:
          path: /processBill
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  tableName: "bill-table-${sls:stage}"
  serverless-offline:
    httpPort: 8000
    tsConfigFileLocation: "./tsconfig.build.json"

resources:
  Resources:
    BillTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: txnId
            AttributeType: S
        KeySchema:
          - AttributeName: txnId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
