org: donutranger
app: haris-be
service: mh-billplz
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    BILLPLZ_KEY: c7377ec0-50a6-4436-a8fb-19b3386cece6
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  getBill:
    handler: billplz.getBill
    events:
      - httpApi:
          path: /getBill/{id}
          method: get
  createBill:
    handler:  billplz.createBill
    events:
      - httpApi:
          path: /createBill
          method: post

plugins:
- serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
