org: donutranger
app: haris-be
service: mh-billplz
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors: true
  environment: ${file(env.${opt:stage, self:provider.stage}.json)}

functions:
  getBill:
    handler: handlers.getBill
    events:
      - httpApi:
          path: /getBill/{id}
          method: get
  createBill:
    handler:  handlers.createBill
    events:
      - httpApi:
          path: /createBill
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 8000
    tsConfigFileLocation: './tsconfig.build.json'
