org: donutranger
app: haris-be
service: mh-billplz
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors: true
  environment: ${file(env.${opt:stage, self:provider.stage}.json)}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  getBill:
    handler: billplz.getBill
    events:
      - httpApi:
          path: /getBill/{id}
          method: get
  createBill:
    handler:  billplz.createBill
    events:
      - httpApi:
          path: /createBill
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 8000
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'
